"""
app/services/sanctions_service.py — Deterministic OFAC sanctioned-address interception (USP 2).

Two complementary risk signals /docs/ml.md:
  * ML behavioral signal  — /risk scores on-chain behavior via the 92f model.
  * Sanctions known-bad signal — a committed curated registry of OFAC SDN
    digital-currency addresses (app/data/sanctions_seed.json, generated by
    scripts/build_sanctions_seed.py from the official Sanctions List Service).

This module:
  * loads the curated seed into an in-memory lookup (no network dependency),
  * exposes the hard-block override response for matched addresses (critical,
    score=1.0, risk_source=sanctions_override — regardless of what ML would say),
  * best-effort consults the Redis risk registry for operationally-seeded
    designations that are not yet in the committed file,
  * seeds the curated list into the Redis risk registry (risk:{chain}:{addr})
    at startup so /check-wallet hot paths also hard-block sanctioned addresses.

Chain keys are normalized uppercase (BTC/ETH); addresses are matched
case-insensitively after stripping.  The seed's EIP-55 / base58check validation
happened at generation time (scripts/build_sanctions_seed.py).
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from redis.asyncio import Redis

from app.schemas.common import Chain, EvidenceDirection, RiskTier
from app.schemas.wallet import RiskEvidence, RiskResponse
from app.services import registry_service

logger = logging.getLogger(__name__)

_SEED_PATH = Path(__file__).resolve().parent.parent / "data" / "sanctions_seed.json"
SANCTIONED_REGISTRY_TTL = 90 * 24 * 3600  # 90 days; re-seeded at every startup
OVERRIDE_EVIDENCE_FEATURE = "sanctions_interception"

_seed: Optional[dict[str, Any]] = None
_lookup: dict[tuple[str, str], dict[str, Any]] = {}


def _load_seed() -> dict[str, Any]:
    """Load and index the curated sanctions seed (cached)."""
    global _seed, _lookup
    if _seed is not None:
        return _seed
    if not _SEED_PATH.exists():
        logger.error("sanctions_seed_missing", extra={"path": str(_SEED_PATH)})
        _seed = {}
        return _seed
    _seed = json.loads(_SEED_PATH.read_text(encoding="utf-8"))
    _lookup = {}
    for ent in _seed.get("designations", []):
        for addr in ent.get("addresses", []):
            _lookup[(addr["chain"].upper(), addr["address"].strip().lower())] = {
                "designation": ent.get("designation", ""),
                "ofac_list": ent.get("list", "SDN"),
                "programs": list(ent.get("programs", [])),
                "uid": ent.get("uid", ""),
                "chain": addr["chain"].upper(),
                "address": addr["address"].strip(),
            }
    logger.info(
        "sanctions_seed_loaded",
        extra={"path": str(_SEED_PATH), "addresses": len(_lookup), "entities": len(_seed.get("designations", []))},
    )
    return _seed


def curated_address_count() -> int:
    """Number of deliberately curated sanctioned addresses in the committed seed."""
    return sum(len(ent.get("addresses", [])) for ent in _load_seed().get("designations", []))


def lookup_sanctioned(chain: str | Chain, address: str) -> Optional[dict[str, Any]]:
    """Return designation metadata for a sanctioned address, else None.

    Deterministic in-memory lookup over the committed curated seed.
    """
    if not address or not address.strip():
        return None
    chain_key = chain.value if isinstance(chain, Chain) else chain.upper()
    _load_seed()
    return _lookup.get((chain_key, address.strip().lower()))


async def lookup_registry_designation(
    redis_client: Redis, chain: str | Chain, address: str
) -> Optional[dict[str, Any]]:
    """Best-effort consult of the Redis registry for operationally-seeded designations."""
    chain_key = chain.value if isinstance(chain, Chain) else chain.upper()
    entry = await registry_service.get_risk_entry(redis_client, chain_key, address)
    if not entry or entry.get("source") != "ofac_sdn":
        return None
    d = entry.get("designation") or {}
    return {
        "designation": d.get("designation", "OFAC-designated"),
        "ofac_list": d.get("list", "SDN"),
        "programs": list(d.get("programs", [])) if d.get("programs") else [],
        "uid": d.get("uid", ""),
        "chain": chain_key,
        "address": address.strip(),
    }


def build_sanctions_override_response(sanction: dict[str, Any]) -> RiskResponse:
    """Construct the hard-block RiskResponse for a sanctioned address.

    risk_tier=critical, risk_score=1.0, risk_source=sanctions_override — regardless
    of what the ML model would output.  Evidence credits the interception with the
    designation / sanctions-list detail.
    """
    detail = " · ".join(
        part for part in (sanction.get("designation"), sanction.get("ofac_list"), ", ".join(sanction.get("programs", [])) if sanction.get("programs") else "") if part
    )
    logger.info(
        "sanctions_interception",
        extra={
            "address": sanction.get("address"),
            "chain": sanction.get("chain"),
            "designation": sanction.get("designation"),
            "list": sanction.get("ofac_list"),
        },
    )
    return RiskResponse(
        risk_score=1.0,
        risk_tier=RiskTier.critical,
        risk_source="sanctions_override",
        evidence=[
            RiskEvidence(
                feature_name=OVERRIDE_EVIDENCE_FEATURE,
                contribution=1.0,
                direction=EvidenceDirection.increases_risk,
                detail=detail,
            )
        ],
    )


async def seed_redis(redis_client: Optional[Redis] = None) -> int:
    """Write every curated sanctioned address into the Redis risk registry.

    Each entry: score=1.0, tier=critical, source=ofac_sdn, designation metadata.
    Persisted with a long TTL so /check-wallet hot paths hard-block the address.
    """
    client = redis_client if redis_client is not None else registry_service.get_redis_client()
    seed = _load_seed()
    count = 0
    for ent in seed.get("designations", []):
        designation = {
            "designation": ent.get("designation", ""),
            "list": ent.get("list", "SDN"),
            "programs": ent.get("programs", []),
            "uid": ent.get("uid", ""),
        }
        for addr in ent.get("addresses", []):
            await registry_service.set_risk_entry(
                redis_client=client,
                chain=addr["chain"],
                address=addr["address"],
                score=1.0,
                tier=RiskTier.critical,
                case_ref=None,
                ttl=SANCTIONED_REGISTRY_TTL,
                source="ofac_sdn",
                designation=designation,
            )
            count += 1
    logger.info(
        "sanctions_registry_seeded",
        extra={
            "count": count,
            "flagged_at": datetime.now(timezone.utc).isoformat(),
        },
    )
    return count


async def ensure_redis_seeded() -> None:
    """Startup hook: seed Redis best-effort; never block or crash startup on failure."""
    try:
        await seed_redis()
    except Exception as exc:  # noqa: BLE001 — registry seeding must never fail startup
        logger.warning("sanctions_registry_seed_failed", extra={"error": str(exc)})