/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard/alerts'
import { Route as DashboardCasesRouteImport } from './routes/dashboard/cases'
import { Route as DashboardCrossVictimRouteImport } from './routes/dashboard/cross-victim'
import { Route as DashboardDepositRouteImport } from './routes/dashboard/deposit'
import { Route as DashboardEvidenceRouteImport } from './routes/dashboard/evidence'
import { Route as DashboardInvestigationRouteImport } from './routes/dashboard/investigation'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardRiskRouteImport } from './routes/dashboard/risk'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSignalsRouteImport } from './routes/dashboard/signals'
import { Route as DashboardTraceRouteImport } from './routes/dashboard/trace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesRoute = DashboardCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrossVictimRoute = DashboardCrossVictimRouteImport.update({
  id: '/cross-victim',
  path: '/cross-victim',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvidenceRoute = DashboardEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestigationRoute = DashboardInvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRiskRoute = DashboardRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignalsRoute = DashboardSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTraceRoute = DashboardTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/cross-victim': typeof DashboardCrossVictimRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/investigation': typeof DashboardInvestigationRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/cross-victim': typeof DashboardCrossVictimRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/investigation': typeof DashboardInvestigationRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/cross-victim': typeof DashboardCrossVictimRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/investigation': typeof DashboardInvestigationRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signals': typeof DashboardSignalsRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/cases'
    | '/dashboard/cross-victim'
    | '/dashboard/deposit'
    | '/dashboard/evidence'
    | '/dashboard/investigation'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/dashboard/trace'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/alerts'
    | '/dashboard/cases'
    | '/dashboard/cross-victim'
    | '/dashboard/deposit'
    | '/dashboard/evidence'
    | '/dashboard/investigation'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/dashboard/trace'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/cases'
    | '/dashboard/cross-victim'
    | '/dashboard/deposit'
    | '/dashboard/evidence'
    | '/dashboard/investigation'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/dashboard/trace'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases': {
      id: '/dashboard/cases'
      path: '/cases'
      fullPath: '/dashboard/cases'
      preLoaderRoute: typeof DashboardCasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cross-victim': {
      id: '/dashboard/cross-victim'
      path: '/cross-victim'
      fullPath: '/dashboard/cross-victim'
      preLoaderRoute: typeof DashboardCrossVictimRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit': {
      id: '/dashboard/deposit'
      path: '/deposit'
      fullPath: '/dashboard/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evidence': {
      id: '/dashboard/evidence'
      path: '/evidence'
      fullPath: '/dashboard/evidence'
      preLoaderRoute: typeof DashboardEvidenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/investigation': {
      id: '/dashboard/investigation'
      path: '/investigation'
      fullPath: '/dashboard/investigation'
      preLoaderRoute: typeof DashboardInvestigationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/risk': {
      id: '/dashboard/risk'
      path: '/risk'
      fullPath: '/dashboard/risk'
      preLoaderRoute: typeof DashboardRiskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signals': {
      id: '/dashboard/signals'
      path: '/signals'
      fullPath: '/dashboard/signals'
      preLoaderRoute: typeof DashboardSignalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trace': {
      id: '/dashboard/trace'
      path: '/trace'
      fullPath: '/dashboard/trace'
      preLoaderRoute: typeof DashboardTraceRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardCasesRoute: typeof DashboardCasesRoute
  DashboardCrossVictimRoute: typeof DashboardCrossVictimRoute
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardEvidenceRoute: typeof DashboardEvidenceRoute
  DashboardInvestigationRoute: typeof DashboardInvestigationRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRiskRoute: typeof DashboardRiskRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSignalsRoute: typeof DashboardSignalsRoute
  DashboardTraceRoute: typeof DashboardTraceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardCasesRoute: DashboardCasesRoute,
  DashboardCrossVictimRoute: DashboardCrossVictimRoute,
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardEvidenceRoute: DashboardEvidenceRoute,
  DashboardInvestigationRoute: DashboardInvestigationRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRiskRoute: DashboardRiskRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSignalsRoute: DashboardSignalsRoute,
  DashboardTraceRoute: DashboardTraceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
